# Generated by Django 5.0 on 2023-12-07 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=30, verbose_name='Длительность')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'План абонемента',
                'verbose_name_plural': 'Планы абонементов',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название зала')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название тренировки')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя тренера')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('qualification', models.CharField(blank=True, max_length=30, null=True, verbose_name='Специализация')),
                ('experience', models.CharField(blank=True, max_length=30, null=True, verbose_name='Опыт работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/')),
                ('is_coach', models.BooleanField(blank=True, default=False, verbose_name='без тренера')),
                ('gym', models.ManyToManyField(related_name='Залы', to='main.gym')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30, verbose_name='Время тренировки')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='Количество человек')),
                ('is_busy', models.BooleanField(blank=True, default=False, verbose_name='Время переполнено')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gym')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_payed', models.BooleanField(blank=True, default=False, verbose_name='Статус оплаты')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cardplan')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gym')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='workouts',
            field=models.ManyToManyField(related_name='Тренировки', to='main.workouts'),
        ),
    ]
