# Generated by Django 5.0 on 2023-12-18 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_image_profile_selected_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subscriptionplan'),
        ),
    ]
