# Generated by Django 5.0 on 2023-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_card_coach_remove_card_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
