# Generated by Django 5.0 on 2023-12-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tariff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='internet_amount',
            field=models.IntegerField(default=0, verbose_name='Количество интернета'),
        ),
    ]
