# Generated by Django 5.0 on 2023-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tariff_internet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='minutes_amount',
            field=models.IntegerField(default=0, verbose_name='Количество минут'),
        ),
    ]
