# Generated by Django 5.0 on 2023-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tariff_minutes_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='additional_services',
            field=models.CharField(max_length=100, null=True, verbose_name='Дополнительные услуги'),
        ),
    ]
