# Generated by Django 5.0 on 2023-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tariff_additional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='additional_services',
            field=models.CharField(default='Нет', max_length=100, verbose_name='Дополнительные услуги'),
        ),
    ]
