# Generated by Django 5.0 on 2023-12-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='memory',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Количество памяти'),
        ),
    ]
