# Generated by Django 5.0 on 2023-12-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_shop_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание'),
        ),
    ]
