# Generated by Django 5.0 on 2023-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
