# Generated by Django 5.0 on 2023-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='memory',
            field=models.IntegerField(default=0, verbose_name='Количество памяти'),
        ),
    ]
