# Generated by Django 5.0 on 2023-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_shop_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='phones/', verbose_name='Ссылка на картинку'),
        ),
    ]
