# Generated by Django 5.0 on 2023-12-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/phones/', verbose_name='Ссылка на картинку'),
        ),
    ]
