# Generated by Django 5.0 on 2023-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Ссылка на картинку'),
        ),
    ]
