# Generated by Django 5.0 on 2023-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(max_length=10, null=True, verbose_name='Цвет'),
        ),
    ]
