# Generated by Django 5.0 on 2023-12-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_shop_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
